### ISSUE TITLE
Lab 02:  Code requires newer .NET update

### ISSUE THREAD

**Issue by TesterTesterson1004** [MicrosoftLearning/DP-070-Migrate-Open-Source-Workloads-to-Azure#5]
In Lab-02, Exercise 1,  Task 2,  Step 5:

- When one issues the dotnet run command, you will receive an error:
- 
![image](https://user-images.githubusercontent.com/49700217/132385320-e31708d6-1746-4bf5-89f2-9651036c25fc.png)

- Still receive error if one runs w/elevated sudo privs

Workaround:  

Before running dotnet run command, issue the following commands to update .NET:

sudo apt update
sudo apt install -y dotnet-sdk-3.1

I am not certain if there are other recently updated apps/code in this course that might have the same issue, and if so - should this be something added to the build/setup guide (w/currently specifies 'Install .Net Core 2.2') so that it is inherent to the VM, or would this be more easily resolved by adding an alert/note to the instructions?

**Comment by GraemeMalcolm** [comment]
Added tip
